name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: mbedos/mbed-os-env@stable
    - name: configure
      run: mbed deploy
    - name: build
      run: mbed compile -t GCC_ARM -m K64F
