name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: mbedos/mbed-os-env:stable
    steps:
    - uses: actions/checkout@v2 
    - name: configure
      run: mbed deploy
    - name: build
      run: |
        cd NFC_EEPROM
        mbed compile -t GCC_ARM -m DISCO_L475VG_IOT01A
